name: deployBackend

on:
    push:
        branches: [ main ]
        paths:
        - 'backend/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: azure/login@v1
      with:
          creds: ${{ secrets.AZURECREDENTIALS }}

    # List files in backend directory before deployment
    - name: List files in backend directory before deployment
      run: |
        ls -la backend/

    # Build the backend .NET project
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'  # Use the .NET version your project targets

    - name: Restore dependencies
      run: |
        cd backend
        dotnet restore

    - name: Build the backend
      run: |
        cd backend
        dotnet build --configuration Release

    # Deploy to Azure Function App
    - name: Deploy to Azure Function App
      uses: Azure/functions-action@v1
      with:
        app-name: 'GetResumeCounterEthan'  # Replace with your Azure Function App name
        package: 'backend'  # Adjust based on your .NET version and target framework

    # Azure logout
    - name: Logout
      run: |
        az logout
      if: always()
