name: deployBackend

on:
    push:
        branches: [ main ]
        paths:
        - 'backend/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: azure/login@v1
      with:
          creds: ${{ secrets.AZURECREDENTIALS }}

    # List files in the backend/api directory before deployment
    - name: List files in backend/api directory before deployment
      run: |
        ls -la backend/api/

    # Setup .NET Core SDK
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'  # Specify the appropriate .NET version for your project

    # Restore dependencies
    - name: Restore dependencies
      run: |
        dotnet restore backend/api/api.csproj  # Update to the correct .csproj file

    # Build the backend project
    - name: Build the backend
      run: |
        dotnet build backend/api/api.csproj --configuration Release

    # Publish the backend project
    - name: Publish the backend
      run: |
        dotnet publish backend/api/api.csproj --configuration Release --output backend/api/publish

    # Deploy to Azure Function App
    - name: Deploy to Azure Function App
      uses: Azure/functions-action@v1
      with:
        app-name: 'your-function-app-name'  # Replace with your Azure Function App name
        package: 'backend/api/publish'  # Adjust based on your .NET version and target framework
        publish-profile: ${{ secrets.FUNCTIONAPP_PUBLISH_PROFILE }}

    # Azure logout
    - name: Logout
      run: |
        az logout
      if: always()
