name: DeployBackend
on:
  push:
    branches: [main]
    paths:
      - 'backend/**'

jobs:
  build-and-deploy:
    runs-on: windows-latest
    environment: dev
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v3

      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURECREDENTIALS }}

      - name: 'Retrieve publish profile for deployment'
        id: publishProfileRetrieval
        run: |
          $publishProfiles = az webapp deployment list-publishing-profiles `
            --name "GetResumeCounterEthan" `
            --resource-group "getresumecounterethan4" `
            --subscription "f7f083f1-fcc5-4dee-8439-41c4798dfad2" `
            --xml
        shell: pwsh

      - name: 'Run unit test'
        shell: pwsh
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/tests'
          dotnet test

      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/api/output'
